# model: rnn
model: transformer
train_params:
  epochs: 25
  batch_size: 32
  val_batch_size: 32
  lr: 1e-4
model_params:
  rnn:
    net_class: gru
    hidden_dim: 128
    heads: 4
    dropout: 0.1
    dropout_lin: 0.2
    layers: 2
    bidirectional: false
  transformer:
    feedforward_dim: 1200
    heads: 4
    dropout: 0.1
    dropout_lin: 0.2
    layers: 2


