model: alexnet
#model: resnet
train_param:
  epochs: 25
  batch_size: 32
  val_batch_size: 32
  lr: 1e-4
model_params:
  alexnet:
    image_size: 512
    fc_feat: 512
    conv_feats: [128, 128, 256, 256, 512, 512]
    dropout: 0.2
  resnet:
    dropout: 0.2
    frozen: 5


