model: alexnet
#model: resnet
train_params:
  epochs: 1
  batch_size: 16
  val_batch_size: 32
  lr: 1e-4
model_params:
  alexnet:
    image_size: 128
    fc_feat: 512
    conv_feats: [128, 128, 256, 256, 512, 512]
    dropout: 0.2
  resnet:
    image_size: 512
    frozen: 5


